name: General Test
on:
  push:
    branches:
      - main
    paths:
      - "ai_infra_bench/**"
      - "aib-dataset/**"
      - ".github/workflows/test.yml"
      - "tests/**"
      - "test/**"
      - "pyproject.toml"
  pull_request:
  workflow_dispatch:

jobs:
  test-mode:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip

      - name: Install dependencies
        run: |
          pip install -U pip setuptools wheel
          pip install -e ./aib-dataset
          pip install -e . pytest

      - name: Run tests
        run: |
          python -m pytest -q
