name: General Test
on:
  push:
    branches:
      - main
    paths:
      - "ai_infra_bench/**"
      - ".github/workflows/test.yml"
  pull_request:
  workflow_dispatch:

jobs:
  test-mode:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install dependencies
        run: |
          pip install -U pip setuptools wheel
          pip install -e .

      - name: Run tests
        run: |
          cd test/modes
          python3 -m unittest

  test-sgl:
    runs-on: ubuntu-latest
    steps:
      - name: Test-Env
        run: echo ${GITHUB_ACTIONS}
